import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home({ pikachu }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Lektion3 | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Hej från index</h1>
      <Image
        width={100}
        height={100}
        src={pikachu.sprites.front_default}
        alt={pikachu.name}
      />
    </div>
  );
}

export async function getStaticProps() {
  const res = await fetch("https://pokeapi.co/api/v2/pokemon/pikachu");
  const data = await res.json();

  console.log(data);
  return { props: { pikachu: data } };
}
